#!/usr/bin/env python3
"""Write COHORT.md: the per-material table of the 40 drawn slabs (draw, DFT status, timings, grid, QC, decision)."""
import csv
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent


def rd(p):
    return list(csv.DictReader(open(HERE / p, encoding="utf-8")))


drawn = rd("selection/drawn.csv")
st = {r["material_id"]: r for r in rd("runs/STATUS.csv")}
qc = {r["material_id"]: r for r in rd("qc/qc.csv")}
dec = {d["material_id"]: d["decision"] for d in json.loads((HERE / "cohort_log.json").read_text())["decisions"]}
coh = {r["material_id"]: r["cohort_rank"] for r in rd("cohort.csv")}
funnel = json.loads((HERE / "selection" / "funnel.json").read_text())["counts"]
lines = ["# Self-computed slab cohort: inputs, DFT status and input QC", "",
         "Generated by `write_cohort_md.py` from `selection/drawn.csv`, `runs/STATUS.csv`, `qc/qc.csv` and",
         "`cohort_log.json`. Inputs and input QC only; no HB quantity has been computed.", "",
         f"Funnel: {' -> '.join(f'{v:,}' for v in funnel.values())} "
         f"({', '.join(funnel)}).", "",
         f"Drawn 40; converged {sum(1 for r in st.values() if r['status'].startswith('converged'))} "
         f"(all with ALGO = Normal); NELM twice (ALGO = Normal, then the declared ALGO = All fallback) "
         f"{sum(1 for r in st.values() if r['status'] == 'nelm_twice')}; input QC pass "
         f"{sum(1 for r in qc.values() if r['qc_pass'] == '1')} of {len(qc)}; **cohort N = {len(coh)}**.", "",
         "| draw | cohort | material_id | formula | hkl | atoms | fine grid (= estimate) | k | status | SCF | s | R | decision |",
         "|---:|---:|---|---|---|---:|---|---|---|---:|---:|---:|---|"]
for r in drawn:
    m = r["material_id"]
    q = qc.get(m, {})
    s = st[m]
    grid = q.get("CHGCAR_grid", "")
    eq = "yes" if grid and grid == r["ngf"] else ("" if not grid else "NO")
    sec = q.get("elapsed_s") or s.get("seconds", "")
    lines.append(f"| {r['draw_rank']} | {coh.get(m, '')} | `{m}` | {r['reduced_formula']} | ({r['miller']}) | {r['natoms']} | "
                 f"{grid or r['ngf'] + ' (est.)'} {('(' + eq + ')') if eq else ''} | {r['kpoints']} | {s['status']} | "
                 f"{q.get('scf_steps', '')} | {float(sec):.0f} | {q.get('R_total_over_sumZ', '')} | {dec[m]} |")
lines += ["", "`s` is VASP's elapsed time of the final run on 36 ranks (for `nelm_twice`, the job's time for both runs). "
          "`R` is (sum(AECCAR0) + sum(AECCAR2)) / N_grid / sum(Z), accepted in [0.80, 50] (PROTOCOL.md section 6).", ""]
(HERE / "COHORT.md").write_text("\n".join(lines), encoding="utf-8", newline="\n")
print("\n".join(lines[:12]))
