#!/usr/bin/env python3
"""Deterministically integrate completed P1/P2 evidence into the active manuscript.

This script performs exact text replacements and refuses to edit if the expected
pre-integration text is absent. It does not alter numerical result files.
"""
from pathlib import Path

P = Path('paper/MANUSCRIPT_TOP_JOURNAL_POLISHED_20260911.md')
text = P.read_text(encoding='utf-8')

replacements = [
(
"Numerical agreement with a fixed reference does not by itself establish that a downstream scientific interpretation is robust to small input changes. We investigate this distinction for Bader charges derived from compressed electronic densities using 6,343 frozen reconstructions of 254 bulk and slab systems, together with an earlier frozen 63-system external confirmation. QoI Stability Qualification (QSQ) screens reference sensitivity using five fixed-seed perturbations. On the common base tolerance ladder, 616 of 740 numerical no-pass decisions (83.2%) at $10^{-4}\\,e$ and 296 of 524 (56.5%) at $10^{-3}\\,e$ occur on material-threshold pairs rejected by QSQ. The previously higher fractions of 97.2% and 95.5% arise in a full record with eligibility-targeted tight-ladder access, demonstrating that search opportunity must also be controlled. A retrospective four-seed/one-seed holdout audit detects further exceedances in 18 of 338 admitted material-splits at the strictest threshold; this is not independent validation of the deployed five-seed rule. Re-derived Bader charges respond irregularly through basin migration, whereas Hartree-potential error behaves more regularly; realized-distortion matching separates nominal-tolerance effects from residual codec differences. The results motivate reporting reference stability and fixed-pipeline fidelity as distinct benchmark axes. QSQ provides an auditable operational screen, while calibrated robust certification requires independent validation of the stated perturbation model.",
"Numerical agreement with a fixed reference does not by itself establish that a downstream scientific interpretation is robust to small input changes. We investigate this distinction for Bader charges derived from compressed electronic densities using 6,343 frozen reconstructions of 254 bulk and slab systems, an additive 1,332-reconstruction common-tight-ladder completion, and an earlier frozen 63-system external confirmation. QoI Stability Qualification (QSQ) screens reference sensitivity using five fixed-seed perturbations. Equalizing tight-ladder search opportunity preserves strong risk stratification: at $10^{-3}\\,e$, failure to find a numerically passing reconstruction occurs for 3.3% of eligible versus 66.4% of screen-rejected material–codec pairs. We then prospectively test the frozen five-seed gate using 59 pre-registered fresh perturbations per development material (14,986/14,986 successful trials). At the primary $10^{-3}\\,e$ endpoint, fresh-threshold exceedance risk is 1.60% in the 143 admitted materials versus 81.33% in the 111 screen-rejected materials, a 50.83-fold risk ratio under the declared iid-uniform perturbation model. Re-derived Bader charges respond irregularly through basin migration, whereas Hartree-potential error behaves more regularly; realized-distortion matching separates nominal-tolerance effects from residual codec differences. These results establish QSQ as a prospectively validated empirical risk-stratification screen for this stated perturbation model while preserving a strict distinction between reference robustness and fixed-pipeline compression fidelity. Finite perturbation panels do not constitute worst-case stability guarantees."
),
(
"Here we analyse 6,343 frozen reconstructions of 254 development densities (186 bulk systems and 68 slabs) compressed with ZFP, SZ3 and SPERR over base and tight tolerance ladders. We introduce **QoI Stability Qualification (QSQ)** to measure a material-specific Bader stability scale before codec certification, re-derive Bader basins after every reconstruction, decompose representative errors into fixed-domain and domain-migration contributions, and compare codecs after matching by realized rather than nominal $L_\\infty$ distortion. We then apply the frozen decision rules, without retuning, to an untouched external cohort of 63 systems. The resulting framework reports reference qualification alongside rate-fidelity performance. The new research audit also checks whether unequal tolerance-ladder access and finite probe coverage affect this interpretation; previously observed external outcomes are not reused as untouched tests of a revised method.",
"Here we analyse 6,343 frozen reconstructions of 254 development densities (186 bulk systems and 68 slabs) compressed with ZFP, SZ3 and SPERR over base and tight tolerance ladders. We introduce **QoI Stability Qualification (QSQ)** to measure a material-specific Bader stability scale before codec certification, re-derive Bader basins after every reconstruction, decompose representative errors into fixed-domain and domain-migration contributions, and compare codecs after matching by realized rather than nominal $L_\\infty$ distortion. We then complete the tight ladder for the 111 development materials that originally lacked it, adding 1,332 pre-specified reconstructions so that all 254 materials receive the same tight-search opportunity. Finally, without modifying the deployed five-seed gate, we run 59 pre-registered fresh perturbations per development material to test its prospective risk discrimination. The previously observed 63-system external cohort remains a separate frozen confirmation of the operational pipeline and is not relabelled as untouched validation of these later research extensions."
),
(
"The tight extension creates 214 additional numerical passes at $10^{-3}\\,e$, all in the eligible group. The original >95% result is therefore ladder-design-sensitive and cannot be interpreted as a design-independent causal misattribution rate. At $10^{-4}\\,e$, the base-only 83.2% fraction must also be read against 81.9% non-evaluable prevalence. The frozen QSQ labels remain unchanged; the audit changes the strength of the inference. Full decisions, per-codec summaries, material-cluster bootstrap intervals and search-opportunity transitions are provided in `analysis/research_upgrade/`.",
"The historical eligibility-targeted extension creates 214 additional numerical passes at $10^{-3}\\,e$, all in the eligible group. The original >95% result is therefore ladder-design-sensitive and cannot be interpreted as a design-independent causal misattribution rate. We addressed this directly by prospectively completing the same four tight settings for the 111 previously uncovered materials, adding 1,332 reconstructions with 1,332/1,332 successful outcomes. Under the completed common tight ladder, failure to find any numerical pass occurs in 3.3% of eligible versus 66.4% of QSQ screen-rejected material–codec pairs at $10^{-3}\\,e$ (risk ratio 20.34). The corresponding risks are 10.9% versus 79.3% at $10^{-4}\\,e$ (7.30-fold) and 0.0% versus 68.0% at $10^{-2}\\,e$. Thus, QSQ's association with hard-to-satisfy downstream targets persists after equalizing search opportunity, although this result alone does not validate unseen reference perturbations or assign causality to individual codec discrepancies."
),
(
"### Reused-seed holdouts reveal finite-panel fragility\n\nA retrospective four-training-seed/one-held-out-seed audit on the 319-system stability universe yields 18/338 (5.33%), 12/947 (1.27%) and 1/1441 (0.0694%) held-out exceedances among admitted material-splits at 1e-4, 1e-3 and 1e-2 e. Each material contributes five correlated splits; bootstrap resampling uses materials rather than treating splits as independent systems. Since all five seeds were already used in development, these results diagnose four-seed screening fragility and do not estimate the prospective error rate of the deployed five-seed QSQ rule. Fresh-seed confirmation is specified separately and has not yet been executed.",
"### The frozen QSQ gate prospectively stratifies unseen perturbation risk\n\nWe prospectively challenged the deployed five-seed QSQ gate with 59 pre-registered fresh iid-uniform perturbations for each of the 254 development materials, using the same material-specific amplitude and no retuning. All 14,986 planned trials produced valid Bader outcomes. At the pre-specified primary threshold of $10^{-3}\\,e$, QSQ admits 143/254 materials (56.3%). Among their 8,437 fresh trials, 135 exceed the threshold, corresponding to a 1.600% trial-level exceedance risk (95% material-cluster bootstrap interval, 0.782–2.596%). Among the 111 screen-rejected materials, 5,326 of 6,549 fresh trials exceed the threshold, a risk of 81.325% (75.981–86.257%). The rejected-to-eligible risk ratio is 50.83, and 20/143 admitted materials versus 110/111 rejected materials show at least one fresh exceedance.\n\nThe prespecified secondary thresholds show the same separation with different acceptance coverage. At $10^{-4}\\,e$, 46/254 materials are admitted and fresh exceedance risks are 4.016% versus 86.938% (21.65-fold). At $10^{-2}\\,e$, 229/254 are admitted and risks are 0.148% versus 79.593% (537.69-fold). Because the same 59 response vectors support all three thresholds, these are not three independent experiments. The fresh seeds validate prospective discrimination conditional on the development materials and declared iid-uniform perturbation model; they do not establish worst-case stability, simultaneous per-material guarantees, or new-material generalization. A material with zero exceedances in 59 valid iid draws has a one-sided 95% exact per-cell upper bound of approximately 4.95% under the stated Bernoulli model."
),
(
"Scientific-compression benchmarks should distinguish numerical agreement with a specified reference from robustness of the reference interpretation. Our common-ladder audit shows that the magnitude of label reclassification is sensitive to which codec settings were made available. The original full-record percentages remain reproducible descriptive statistics, but do not by themselves identify causal misattribution or establish the predictive value of a stability gate. Useful qualification must be validated by held-out risk, useful coverage and computational cost, not by a large rejection fraction alone.",
"Scientific-compression benchmarks should distinguish numerical agreement with a specified reference from robustness of the reference interpretation. Our completed common tight ladder first removes a benchmark-design confound: QSQ-rejected targets remain substantially more likely than eligible targets to lack a numerical pass after every material receives the same pre-specified tight-search opportunity. More importantly, the 14,986-trial prospective perturbation test shows that the frozen five-seed gate strongly separates low- from high-risk reference responses under the declared perturbation model, with 56.3% acceptance coverage and a 50.83-fold rejected-to-eligible risk ratio at the primary $10^{-3}\\,e$ endpoint. The central empirical contribution is therefore prospective risk stratification rather than a large retrospective reclassification percentage."
),
(
"The QSQ perturbation test illustrates a second consequence of the framework: the stability test itself is part of the measurement contract. The archived float32 probe was numerically small but structurally inappropriate because it largely preserved the ordering that drives the on-grid partition. A valid qualification procedure must therefore probe the failure modes of the downstream operator, not merely impose an arbitrarily small perturbation. The five-seed maximum is conservative relative to using any one of those seeds, but not an upper bound on unseen perturbations. It defines an auditable empirical screen, not an intrinsic material constant or a calibrated probability of safety. The reused-seed audit motivates genuinely independent validation. Moreover, separate reference-response and reconstruction-error tests below the same tolerance do not automatically imply a combined robust error below that tolerance; an explicit target and error budget are needed.",
"The QSQ perturbation test illustrates a second consequence of the framework: the stability test itself is part of the measurement contract. The archived float32 probe was numerically small but structurally inappropriate because it largely preserved the ordering that drives the on-grid partition. A valid qualification procedure must therefore probe the failure modes of the downstream operator, not merely impose an arbitrarily small perturbation. The five-seed maximum is conservative relative to using any one of those seeds, but not an upper bound on unseen perturbations. The prospective 59-seed test now provides direct empirical evidence that this frozen screen is strongly discriminative for unseen draws from the same declared perturbation model, while also revealing a non-zero 1.60% exceedance rate among accepted trials at the primary threshold. QSQ should therefore be interpreted as a validated risk-stratification screen, not an intrinsic material constant or worst-case certificate. Moreover, separate reference-response and reconstruction-error tests below the same tolerance do not automatically imply a combined robust error below that tolerance; an explicit target and error budget are needed."
),
(
"### Common-ladder and retrospective seed-holdout audits\n\nThe common-ladder audit reads the frozen master table without changing eligibility, thresholds or reconstruction outputs. We compare the full record, base-only rows, and the subset of base rungs observed for all three codecs within each material. Numerical pass means that at least one available reconstruction has re-derived Bader error below the threshold; no-pass means that no available rung passes, not that the codec could never pass under another setting. Missing material-codec observations are labelled unavailable. The audit validates all stored flags and reproduces the original Figure 3 counts before computing controls.\n\nFor seed holdout, each of five seeds is withheld in turn and the remaining four define the retrospective screen. A false-safe split passes the four-seed screen but exceeds the threshold on the held-out seed. We use 2,000 deterministic material-cluster bootstrap replicates for descriptive intervals. These reused-seed diagnostics are not prospective tests, and the external descriptive subset is not substituted for the 63-system confirmatory population. Source hashes and complete tables are in `analysis/research_upgrade/`.",
"### Common-ladder completion and prospective perturbation validation\n\nThe common-ladder audit first reads the frozen master table without changing eligibility, thresholds or reconstruction outputs. We compare the full record, base-only rows, and the subset of base rungs observed for all three codecs within each material. We then prospectively complete the four pre-existing tight settings for all 111 materials that did not originally receive them, for 1,332 additive material–codec–setting evaluations. Numerical pass means that at least one available reconstruction has re-derived Bader error below the threshold; no-pass means that no evaluated rung passes, not that the codec could never pass under an untested setting. The historical 6,343-row table remains unchanged, and the additive common-tight results are stored separately. Material-cluster bootstrap intervals preserve codec observations within resampled materials.\n\nFor prospective QSQ validation, the original five-seed gate, thresholds and material-specific perturbation amplitudes were frozen before execution. Each of the 254 development materials received 59 fresh seed labels (10000–10058) with deterministic PCG64 stream seeds generated from SHA-256 over material identity, perturbation family and seed label. The work order contained 14,986 unique material–seed keys and was hashed before execution. The primary endpoint was fresh Bader response $\\geq10^{-3}\\,e$; $10^{-4}$ and $10^{-2}\\,e$ were pre-specified secondary endpoints. We report trial-level exceedance risk separately in QSQ-eligible and screen-rejected groups, acceptance coverage, the rejected-to-eligible risk ratio and material-cluster bootstrap intervals. The five-seed rule was not modified after observing fresh outcomes. All 14,986 trials were successfully accounted. Source hashes, immutable manifests and complete machine-readable summaries are stored in `validation/qsq_prospective/p2_fresh_probes/` and `analysis/research_upgrade/`."
),
(
"Frozen benchmark tables, QSQ stability outputs, binary-to-three-state reclassification data, mechanism decompositions, realized-distortion matching analyses, external confirmatory results, R figure sources and claim–evidence records are versioned in the public `stloendays/QoI` repository.",
"Frozen benchmark tables, additive common-tight-ladder measurements, prospective 59-seed QSQ validation outputs, QSQ stability outputs, binary-to-three-state reclassification data, mechanism decompositions, realized-distortion matching analyses, external confirmatory results, R figure sources and claim–evidence records are versioned in the public `stloendays/QoI` repository."
),
]

for old, new in replacements:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f'Expected exactly one manuscript match, found {count}: {old[:100]!r}')
    text = text.replace(old, new)

P.write_text(text, encoding='utf-8')
print(f'P1_P2_MANUSCRIPT_INTEGRATION_PASS replacements={len(replacements)}')
