from __future__ import annotations
import re, hashlib, sys
from pathlib import Path

src = Path(sys.argv[1]); out = Path(sys.argv[2])
text = src.read_text(encoding='utf-8')
text = re.sub(r'<!--.*?-->\n?', '', text, flags=re.S)
text = text.replace('pre-registered', 'pre-specified')
text = text.replace('RuO$_2$ CO$_2$RR', 'RuO₂ CO₂RR')
text = text.replace('$\nho=0.995$', '$\\rho=0.995$').replace('$\nho=0.754$', '$\\rho=0.754$')

m = re.search(r'(?s)(## Abstract\n\n)(.*?)(\n\n\*\*Keywords:\*\*)', text)
if not m: raise SystemExit('Abstract block not found')
a = m.group(2)
a = re.sub(r'Across 254 development systems compressed with ZFP, SZ3 and SPERR, completing the same tight search ladder for all materials added 1,332/1,332 successful reconstructions and showed that, at \$10\^{-3}\\,e\$, failure to find a numerical pass occurs for 3\.3% of QSQ-eligible versus 66\.4% of screen-rejected material–codec pairs \(20\.34-fold\)\.\s*', '', a)
a = a.replace('We then froze the five-seed QSQ gate and challenged it prospectively with 59 pre-specified fresh iid-uniform perturbations per material (14,986/14,986 valid trials).','We froze the five-seed QSQ gate and challenged it prospectively with 59 fresh iid-uniform perturbations per material (14,986 valid trials).')
text = text[:m.start(2)] + a + text[m.end(2):]
text = text.replace('Here we ask a logically prior question to conventional QoI-aware compression: **when is a requested downstream tolerance itself a valid benchmark?** We study Bader charge','Here we address this benchmark-validity problem using Bader charge')

start='### Identical field perturbations propagate differently through downstream operators\n\n'; end='\n\n### Reference stability and numerical agreement are distinct benchmark axes'
s=text.find(start); e=text.find(end,s)
if s<0 or e<0: raise SystemExit('control section not found')
controls='''### Downstream operators respond differently to the same field perturbation\n\nThe same reconstructed density can be highly faithful for one observable and unreliable for another because downstream operators have different mathematical structure (Fig. 2). Among 3,205 reconstructions with an absolute electron-count deviation below $10^{-4}\\,e$ and a finite re-derived Bader result, 1,383 (43.15%) still have a Bader error of at least $10^{-3}\\,e$. The periodic Hartree potential is nonlocal but linear and behaves more regularly: across 6,270 reconstruction-gate-passing rows, its error scales approximately linearly with realized density perturbation (pooled log–log exponent 1.02; median material-level $R^2$ = 0.997, 0.994 and 0.996 for ZFP, SZ3 and SPERR).\n\nRe-derived Bader charge is less regular: only 32.4% of material–codec tolerance ladders are strictly monotone, local response exponents span −9.3 to +14.1, and matched-Hartree bins retain broad Bader-error dispersion. These controls are not the central novelty; they establish why the downstream analysis must be included explicitly in the benchmark. Full control analyses are reported in Supplementary Tables S8–S9 and Supplementary Fig. S3.'''
text=text[:s]+controls+text[e:]
text=text.replace('### Reference stability and numerical agreement are distinct benchmark axes','### QSQ qualification separates benchmark validity from codec agreement')
old=('Equalizing search opportunity added 1,332/1,332 successful reconstructions. At the primary $10^{-3}\\,e$ contract, no-pass risk remained sharply separated: 3.3% for QSQ-eligible versus 66.4% for screen-rejected material–codec pairs, a 20.34-fold ratio. The prospective test was stronger still. Across 14,986/14,986 valid fresh perturbations, QSQ admitted 143/254 materials (56.3% coverage); admitted materials showed 135/8,437 threshold exceedances (1.600%), whereas screen-rejected materials showed 5,326/6,549 (81.325%), giving a 50.83-fold rejected-to-eligible risk ratio. The same directional separation held at the two pre-specified secondary thresholds. Thus, the central empirical result is prospective risk stratification under a declared perturbation model, not a design-independent claim that a fixed percentage of codec failures is invalid.')
new=('Equalizing search opportunity added 1,332/1,332 successful reconstructions. At the primary $10^{-3}\\,e$ contract, no-pass risk remained sharply separated: 3.3% for QSQ-eligible versus 66.4% for screen-rejected material–codec pairs, a 20.34-fold ratio. Thus, the QSQ association with difficult benchmark targets persists after equalizing codec search opportunity. We next test the stronger question prospectively: whether the frozen gate stratifies unseen downstream response risk under the declared perturbation model.')
if old not in text: raise SystemExit('mixed P1/P2 paragraph not found')
text=text.replace(old,new)

p3_old=('We next tested whether the QSQ stability classification was specific to the primary Bader implementation. A deterministically stratified 24-system panel spanning bulk and slab densities and four frozen stability-floor bands was re-evaluated with independent Henkelman on-grid and near-grid implementations using the same five historical perturbation fields. A first execution blocked 20 systems before solver evaluation because a provenance check compared source-rederived amplitudes with decimal-serialized historical values at binary-ULP precision; all 360 blocked cells were classified before an engineering-only retry, and no scientific setting was changed. The retry completed 360/360 cells with zero recorded failures. Across the resolved panel, Henkelman on-grid reproduced the frozen QSQ eligibility classification for all 24 systems at $10^{-4}$, $10^{-3}$ and $10^{-2}\\,e$ (100% agreement; Cohen\'s $\\kappa=1.000$ at each threshold) and preserved the stability-floor ordering (Spearman $\\rho=0.995$). By contrast, Henkelman near-grid agreement was 82.6%, 83.3% and 95.8% across the same thresholds, with $\\rho=0.754$. The QSQ risk stratification is therefore not an artifact of one on-grid implementation on this targeted panel, while the near-grid differences show that the downstream numerical algorithm remains part of the measurement contract. This implementation-transfer test does not establish electronic-structure grid convergence or a unique physical Bader reference (Supplementary Table S11).')
p3_new=('### QSQ transfers across an independent on-grid Bader implementation\n\nWe tested whether QSQ classification was specific to the primary Bader implementation using a deterministically stratified 24-system panel spanning bulk and slab densities and four frozen stability-floor bands. After an engineering-only retry of pre-solver serialization/provenance blocks, with no change to scientific settings, the independent Henkelman on-grid implementation reproduced QSQ eligibility for all 24 systems at $10^{-4}$, $10^{-3}$ and $10^{-2}\\,e$ (Cohen\'s $\\kappa=1.000$ at each threshold) and preserved stability-floor ordering (Spearman $\\rho=0.995$). Henkelman near-grid agreement was lower at 82.6%, 83.3% and 95.8%, with $\\rho=0.754$. QSQ therefore transfers across an independent on-grid implementation on this targeted panel, while the near-grid differences show that the downstream numerical algorithm remains part of the measurement contract. This test does not establish electronic-structure grid convergence or a unique physical Bader reference (Supplementary Table S11).')
if p3_old not in text: raise SystemExit('P3A paragraph not found')
text=text.replace(p3_old,p3_new)

def sections(block):
    ms=list(re.finditer(r'(?m)^###\s+(.+)$',block)); pre=block[:ms[0].start()] if ms else block; out=[]
    for i,m in enumerate(ms): out.append((m.group(1).strip(),block[m.start():(ms[i+1].start() if i+1<len(ms) else len(block))].rstrip()))
    return pre,out

rm=re.search(r'(?s)(## Results\n)(.*?)(\n## Discussion\n)',text); pre,secs=sections(rm.group(2)); sm={k:v for k,v in secs}
order=['Downstream operators respond differently to the same field perturbation','QSQ qualification separates benchmark validity from codec agreement','Prospective validation quantifies the separation across thresholds','A valid stability probe must excite the numerical failure mode','QSQ transfers across an independent on-grid Bader implementation','A coarse chemical direction can remain stable outside a strict numerical contract','Basin migration provides a Bader-specific mechanism for irregular amplification','The strictest certified regime approaches the analysis floor','Realized distortion, not nominal tolerance, is required for fair codec comparison','Stability-qualified rate–fidelity rankings depend on the scientific contract','Frozen decision rules reproduce on an untouched external cohort']
if set(sm)!=set(order): raise SystemExit(f'Results mismatch {set(sm)^set(order)}')
text=text[:rm.start(2)]+'\n'+'\n\n'.join(sm[k] for k in order)+'\n'+text[rm.end(2):]

dold=("The principal result of this study is not that pointwise reconstruction error can propagate irregularly into a downstream QoI; that is already established in scientific compression and numerical analysis. The stronger conclusion is that **benchmark scoring itself should be conditioned on whether the downstream QoI can support the requested tolerance under a declared numerical-analysis contract**. In our Bader-charge case study, this claim survives an equal-search control and, more importantly, prospective validation: the frozen QSQ screen separates 1.600% from 81.325% unseen perturbation exceedance risk at the primary $10^{-3}\\,e$ endpoint, while retaining 56.3% of materials. Independent on-grid implementation transfer further shows that the separation is not specific to one software package, whereas near-grid differences make explicit that the analysis semantics remain part of the contract. The equal-search control provides the complementary benchmark-design test: at the same primary threshold, failure to find a numerical pass is 3.3% for eligible versus 66.4% for screen-rejected material–codec pairs (20.34-fold).")
dnew=("The principal result of this study is not that pointwise reconstruction error can propagate irregularly into a downstream QoI; that is already established in scientific compression and numerical analysis. The stronger conclusion is that **benchmark scoring itself should be conditioned on whether the downstream QoI can support the requested tolerance under a declared numerical-analysis contract**. At the primary $10^{-3}\\,e$ endpoint, the equal-search control yields a 20.34-fold separation in no-pass risk, while the prospective perturbation test yields a 50.83-fold separation in unseen exceedance risk. Independent on-grid implementation transfer shows that this qualification is not specific to one software package under matched analysis semantics, whereas the near-grid comparison makes explicit that those semantics remain part of the contract.")
if dold not in text: raise SystemExit('discussion opening not found')
text=text.replace(dold,dnew)

mm=re.search(r'(?s)(## Methods\n)(.*?)(\n## Data and code availability\n)',text); pre,msecs=sections(mm.group(2)); mmap={k:v for k,v in msecs}
morder=['Benchmark design','Realized reconstruction distortion','Control observables','Re-derived Bader charge','QoI Stability Qualification and eligibility','Historical binary-to-three-state sensitivity audit','Common-ladder completion and prospective perturbation validation','Independent implementation-transfer validation','Outcome-blind chemical-decision case study','Bader mechanism decomposition','External confirmation','Reproducibility']
if set(mmap)!=set(morder): raise SystemExit(f'Methods mismatch {set(mmap)^set(morder)}')
text=text[:mm.start(2)]+'\n'+'\n\n'.join(mmap[k] for k in morder)+'\n'+text[mm.end(2):]
text=text.replace('The maximum Bader response is an operational susceptibility scale, historically called the stability floor.','The maximum Bader response is an operational QSQ response scale, historically called the stability floor in frozen data products.')
text=text.replace('The stability floor $f_m$ is the maximum induced Bader deviation across the five probes.','The operational QSQ response scale $f_m$ is the maximum induced Bader deviation across the five probes; frozen data products retain the historical label "stability floor" for provenance.')
repro_old=('Formal figures are generated from versioned R sources and frozen data tables, with PNG, PDF and SVG exported from the same code. The archived float32 qualification probe remains frozen as provenance, while QSQ is the operative reader-facing qualification procedure. Historical repository identifiers `Protocol A` and `Protocol A.1` are retained only where required to reconstruct the development history and frozen data paths. The repository retains the failure registry, stability tables, external manifest, mechanism decompositions, matching outputs, claim–evidence records and chronological analysis history required to reconstruct the reported decisions.')
repro_new=('Formal figures are generated from versioned R sources and frozen data tables, with PNG, PDF and SVG exported from the same code. The archived float32 qualification probe remains frozen as provenance, while QSQ is the operative reader-facing qualification procedure. The private research archive retains the failure registry, stability tables, external manifest, mechanism decompositions, matching outputs, claim–evidence records and chronological analysis history required to reconstruct the reported decisions. Source hashes and immutable execution manifests are preserved for the prospective and implementation-transfer analyses.')
if repro_old not in text: raise SystemExit('repro paragraph not found')
text=text.replace(repro_old,repro_new)
am=re.search(r'(?s)(## Data and code availability\n\n)(.*?)(\n\n## References)',text)
avail=('During manuscript development, the frozen benchmark tables, QSQ validation outputs, mechanism analyses, external confirmation, figure sources and claim–evidence records are maintained in a private version-controlled research archive. A public archival release containing the derived data and analysis code required to reproduce the reported results will be deposited with a persistent DOI no later than publication, subject to any redistribution constraints on upstream source data. Additional review materials can be provided through a controlled-access package when required by the target journal.')
text=text[:am.start(2)]+avail+text[am.end(2):]
text=re.sub(r'\n{4,}','\n\n\n',text).strip()+'\n'
out.write_text(text,encoding='utf-8')
print(hashlib.sha256(text.encode()).hexdigest())